import fs from 'node:fs/promises';import path from 'node:path';import{fileURLToPath}from'node:url';import{execFileSync}from'node:child_process';
import{buildApp,sha256}from'../scripts/package.mjs';import{requireBrowserReceipt}from'../scripts/integrate.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),out=path.resolve(process.argv[2]||path.join(root,'deliverables/保存連携_直接読込版'));
await requireBrowserReceipt('rehab-inventory');
const receipt=JSON.parse(await fs.readFile(path.join(root,'integrations/rehab-inventory/browser-receipt.json'),'utf8'));
if(receipt.launchMode!=='linked-direct')throw Error('Direct-mode browser verification is required');
await fs.mkdir(path.dirname(out),{recursive:true});await fs.mkdir(out,{recursive:false});
const parent=path.join(out,'D_保存連携_直接読込'),stage=await buildApp('rehab-inventory',parent,{mode:'candidate'});
for(const name of await fs.readdir(stage))await fs.rename(path.join(stage,name),path.join(parent,name));await fs.rmdir(stage);
const release=JSON.parse(await fs.readFile(path.join(parent,'release-manifest.json'),'utf8')),book=path.join(parent,release.workbookFileName);
const profile=JSON.parse(execFileSync('python3',[path.join(root,'startup-study/set-profile.py'),book,'linked-direct'],{encoding:'utf8'}));
const generation=JSON.parse(await fs.readFile(path.join(parent,'workbook-generation.json'),'utf8'));generation.startupStudy=profile;generation.workbookSha256=profile.afterSha256;
await fs.writeFile(path.join(parent,'workbook-generation.json'),JSON.stringify(generation,null,2)+'\n');
release.workbookGeneration=generation;release.hashes[release.workbookFileName]=profile.afterSha256;release.hashes['workbook-generation.json']=sha256(await fs.readFile(path.join(parent,'workbook-generation.json')));release.startupStudy={profile:'linked-direct',windowsJustCalcPerformanceVerified:false,browserReceipt:receipt};
await fs.writeFile(path.join(parent,'release-manifest.json'),JSON.stringify(release,null,2)+'\n');
for(const file of ['はじめに.md','結果を比較.html','検証記録.md'])await fs.copyFile(path.join(root,'direct-study',file),path.join(out,file));
await fs.copyFile(path.join(root,'startup-study/summary.js'),path.join(out,'summary.js'));
await fs.copyFile(path.join(root,'verification/direct-study/input-startup-summary.json'),path.join(out,'前回の集計.json'));
await fs.copyFile(path.join(root,'direct-study/前回の集計.js'),path.join(out,'前回の集計.js'));
await fs.writeFile(path.join(out,'direct-study-manifest.json'),JSON.stringify({status:'candidate; Windows / JUST Calc / Edge validation pending',profile,appId:release.appId,dataVersion:2,nativeMaster:JSON.parse(await fs.readFile(path.join(root,'workbook/MVP8th.build.json'),'utf8')),previousSummarySha256:sha256(await fs.readFile(path.join(out,'前回の集計.json'))),browserReceipt:receipt},null,2)+'\n');
console.log(out);
