#!/usr/bin/env node

import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectDirectory = join(scriptDirectory, "..");
const vendorDirectory = join(projectDirectory, "vendor");

const files = {
  pdfMain: {
    name: "pdf.min.js",
    url: "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js",
    sha256: "5b5799e6f8c680663207ac5b42ee14eed2a406fa7af48f50c154f0c0b1566946",
  },
  pdfWorker: {
    name: "pdf.worker.min.js",
    url: "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js",
    sha256: "feabdf309770ed24bba31a5467836cdc8cf639c705af27d52b585b041bb8527b",
  },
  tesseractMain: {
    name: "tesseract.min.js",
    url: "https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js",
    sha256: "000c27d9cd0def655f77b36c72a389c0ab13793aa31cb4d7aab56d09c0afbc7e",
  },
  tesseractWorker: {
    url: "https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/worker.min.js",
    sha256: "576b7df7e3393e137e51849357c9adb53fe7ac1bb69bfa06cf3d61520f182c6d",
  },
  tesseractCore: {
    url: "https://cdn.jsdelivr.net/npm/tesseract.js-core@7.0.0/tesseract-core-lstm.wasm.js",
    sha256: "eef5f8b2f8e20e150680b20adaec4a60babafee3adbe8a94583c81fee46e8680",
  },
  japaneseModel: {
    url: "https://cdn.jsdelivr.net/npm/@tesseract.js-data/jpn@1.0.0/4.0.0_best_int/jpn.traineddata.gz",
    sha256: "2b63ebfbf1484de4a08ce53b29ef98a1c17658a93cbd38acb665d7d316d0be88",
  },
  englishModel: {
    url: "https://cdn.jsdelivr.net/npm/@tesseract.js-data/eng@1.0.0/4.0.0_best_int/eng.traineddata.gz",
    sha256: "45b4cb346724ac1774f1c36f42f182b887bcdb28ebe63e6fff90ac41f3fcff91",
  },
};

async function downloadAndVerify(asset) {
  const response = await fetch(asset.url, { redirect: "follow" });
  if (!response.ok) {
    throw new Error(`Download failed (${response.status}): ${asset.url}`);
  }

  const buffer = Buffer.from(await response.arrayBuffer());
  const actualHash = createHash("sha256").update(buffer).digest("hex");
  if (actualHash !== asset.sha256) {
    throw new Error(
      `SHA-256 mismatch for ${asset.url}\nexpected: ${asset.sha256}\nactual:   ${actualHash}`,
    );
  }
  return buffer;
}

function quoteForScript(value) {
  return JSON.stringify(value)
    .replaceAll("\u2028", "\\u2028")
    .replaceAll("\u2029", "\\u2029");
}

await mkdir(vendorDirectory, { recursive: true });

const downloaded = Object.fromEntries(
  await Promise.all(
    Object.entries(files).map(async ([key, asset]) => [key, await downloadAndVerify(asset)]),
  ),
);

const originalWorkerSource = downloaded.tesseractWorker.toString("utf8");
const workerLanguageBug = 'return"string"==typeof t?t:t.data';
const workerLanguageFix = 'return"string"==typeof t?t:t.code';
if (!originalWorkerSource.includes(workerLanguageBug)) {
  throw new Error("The expected Tesseract.js language-object expression was not found.");
}
const patchedWorkerSource = originalWorkerSource.replace(workerLanguageBug, workerLanguageFix);

await Promise.all([
  writeFile(join(vendorDirectory, files.pdfMain.name), downloaded.pdfMain),
  writeFile(join(vendorDirectory, files.pdfWorker.name), downloaded.pdfWorker),
  writeFile(join(vendorDirectory, files.tesseractMain.name), downloaded.tesseractMain),
]);

const offlineAssetsSource = `/*
 * Generated by scripts/vendor-offline.mjs.
 * Runtime use is completely offline; do not replace these pinned assets with CDN URLs.
 */
(function exposeScanScribeAssets(root) {
  "use strict";
  const assets = {
    versions: Object.freeze({
      pdfjs: "3.11.174",
      tesseract: "7.0.0",
      tesseractCore: "7.0.0",
      languageData: "4.0.0_best_int",
    }),
    tesseractWorkerSource: ${quoteForScript(patchedWorkerSource)},
    tesseractCoreSource: ${quoteForScript(downloaded.tesseractCore.toString("utf8"))},
    models: Object.freeze({
      jpn: ${quoteForScript(downloaded.japaneseModel.toString("base64"))},
      eng: ${quoteForScript(downloaded.englishModel.toString("base64"))},
    }),
  };
  root.ScanScribeAssets = Object.freeze(assets);
})(window);
`;

await writeFile(
  join(vendorDirectory, "offline-ocr-assets.js"),
  offlineAssetsSource,
  "utf8",
);

const manifest = {
  generatedAt: new Date().toISOString(),
  purpose: "Pinned assets for file:// and network-free runtime use",
  bundle: {
    file: "offline-ocr-assets.js",
    sha256: createHash("sha256").update(offlineAssetsSource).digest("hex"),
    bytes: Buffer.byteLength(offlineAssetsSource, "utf8"),
  },
  patches: [
    {
      asset: "tesseractWorker",
      reason: "Initialize language objects by their code when traineddata bytes are supplied directly",
      replacement: "language.data -> language.code in initialize()",
      patchedSha256: createHash("sha256").update(patchedWorkerSource).digest("hex"),
    },
  ],
  assets: Object.fromEntries(
    Object.entries(files).map(([key, asset]) => [key, {
      url: asset.url,
      sha256: asset.sha256,
      bytes: downloaded[key].length,
    }]),
  ),
};

await writeFile(
  join(vendorDirectory, "MANIFEST.json"),
  `${JSON.stringify(manifest, null, 2)}\n`,
  "utf8",
);

const totalBytes = Object.values(downloaded).reduce((sum, value) => sum + value.length, 0);
console.log(`Offline vendor bundle created (${(totalBytes / 1024 / 1024).toFixed(1)} MiB source assets).`);
